name: mse465project
channels:
  - conda-forge
  - defaults
dependencies:
  - abtem=1.0.9=pyhd8ed1ab_0
  - anyio=4.10.0=py311haa95532_0
  - aom=3.12.1=h00a0c3c_0
  - argon2-cffi=25.1.0=py311haa95532_0
  - argon2-cffi-bindings=25.1.0=py311h02ab6af_0
  - ase=3.27.0=pyhd8ed1ab_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=py311haa95532_0
  - attrs=25.4.0=py311haa95532_2
  - babel=2.17.0=py311haa95532_0
  - backports.zstd=1.3.0=py311h71c1bcc_0
  - beautifulsoup4=4.12.3=py311haa95532_0
  - blas=1.0=mkl
  - bleach=6.3.0=py311haa95532_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py311hc5da9e4_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.2.25=h4c7d964_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2026.01.04=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - click=8.3.1=pyha7b4d00_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h214f63a_0
  - cycler=0.12.1=py311haa95532_0
  - cytoolz=1.1.0=py311h3485c13_2
  - dask-core=2025.11.0=pyhcf101f3_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.16=py311h885b0b7_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.3.1=pyhd8ed1ab_1
  - distributed=2025.11.0=pyhcf101f3_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.4=hd7fb8db_0
  - fftw=3.3.10=nompi_h6877c38_112
  - flask=3.1.3=pyhcf101f3_1
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.61.0=py311h02ab6af_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.14.1=hfbffc0b_0
  - fribidi=1.0.16=haf45083_0
  - fsspec=2026.2.0=pyhd8ed1ab_0
  - google-crc32c=1.8.0=py311h178015e_1
  - graphite2=1.3.14=hd77b12b_1
  - h11=0.16.0=py311haa95532_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.0=h3ef6528_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py311haa95532_0
  - httpx=0.28.1=py311haa95532_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py311haa95532_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.31.0=py311h4442805_0
  - ipympl=0.10.0=pyhcf101f3_0
  - ipython=9.10.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jpeg=9f=ha349fce_0
  - json5=0.12.1=py311haa95532_0
  - jsonschema=4.25.1=py311haa95532_0
  - jsonschema-specifications=2025.9.1=py311haa95532_0
  - jupyter-lsp=2.3.0=py311haa95532_0
  - jupyter_client=8.8.0=py311haa95532_0
  - jupyter_core=5.9.1=py311haa95532_0
  - jupyter_events=0.12.0=py311haa95532_1
  - jupyter_server=2.17.0=py311haa95532_1
  - jupyter_server_terminals=0.5.4=py311haa95532_0
  - jupyterlab=4.5.3=py311haa95532_1
  - jupyterlab_pygments=0.3.0=py311haa95532_0
  - jupyterlab_server=2.28.0=py311haa95532_1
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.9=py311h03f52e7_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libavif=1.3.0=h5bd13ec_0
  - libcrc32c=1.1.2=h0e60522_0
  - libdeflate=1.22=h5bf469e_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.86.3=h9bccc14_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc89ec93_0
  - libkrb5=1.22.1=hb237eb7_0
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.54=ha15c746_0
  - libpq=17.6=h64815fc_1
  - libsodium=1.0.20=h83e8143_0
  - libtiff=4.7.1=h3a18249_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - llvmlite=0.46.0=py311h4f568be_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib=3.10.8=py311haa95532_0
  - matplotlib-base=3.10.8=py311h26e45b9_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.1.2=py311haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=2.1.1=py311h300f80d_0
  - mkl_random=1.3.0=py311ha5e6156_0
  - msgpack-python=1.1.2=py311h3fd045d_1
  - mysql-common=9.3.0=h0b12ad4_5
  - mysql-libs=9.3.0=hcb0c519_5
  - nbclient=0.10.4=py311haa95532_0
  - nbconvert-core=7.17.0=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - notebook-shim=0.2.4=py311haa95532_1
  - numba=0.63.1=py311h34437f8_0
  - numcodecs=0.16.5=py311h11fd7f3_0
  - numpy=2.3.5=py311h050da96_0
  - numpy-base=2.3.5=py311h1e017a8_0
  - openssl=3.6.1=hf411b9b_1
  - overrides=7.7.0=py311haa95532_0
  - packaging=25.0=py311haa95532_1
  - pandas=3.0.1=py311h0610301_0
  - pandocfilters=1.5.1=py311haa95532_0
  - parso=0.8.6=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.46=h5740b90_0
  - pillow=12.1.0=py311h6b7a805_0
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=py311haa95532_0
  - prometheus_client=0.21.1=py311haa95532_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py311hf893f09_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py311haa95532_0
  - pyfftw=0.15.1=py311ha468261_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=py311haa95532_0
  - pyqt=6.10.2=py311hbb189eb_0
  - pyqt6-sip=13.11.0=py311h630b2a1_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-fastjsonschema=2.21.2=py311haa95532_0
  - python-json-logger=4.0.0=py311haa95532_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pywin32=311=py311h885b0b7_0
  - pywinpty=2.0.15=py311hd93a960_1
  - pyyaml=6.0.3=py311h3f79411_1
  - pyzmq=27.1.0=py311h7149c55_1
  - qtbase=6.10.2=h7604b34_0
  - qtdeclarative=6.10.2=h1c18438_0
  - qtsvg=6.10.2=h83a203b_0
  - qttools=6.10.2=h3ada859_0
  - qtwebchannel=6.10.2=hdb80409_0
  - qtwebsockets=6.10.2=he9ef41a_0
  - referencing=0.37.0=py311haa95532_0
  - requests=2.32.5=py311haa95532_1
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - rpds-py=0.28.0=py311h114bc41_0
  - scipy=1.17.0=py311h2074b4c_0
  - send2trash=1.8.3=py311haa95532_0
  - setuptools=80.10.2=py311haa95532_0
  - sip=6.15.1=py311h9561cc3_0
  - six=1.17.0=py311haa95532_0
  - sniffio=1.3.1=py311haa95532_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.5=py311haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tabulate=0.9.0=pyhcf101f3_3
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tblib=3.2.2=pyhcf101f3_0
  - terminado=0.18.1=py311haa95532_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=py311haa95532_0
  - tk=8.6.15=hf199647_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py311h02ab6af_0
  - tqdm=4.67.3=pyha7b4d00_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=1.8.0=py311haa95532_0
  - werkzeug=3.1.6=pyhcf101f3_0
  - wheel=0.46.3=py311haa95532_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=haa95532_5
  - wrapt=2.1.1=py311h3485c13_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - zarr=3.1.5=pyhcf101f3_0
  - zeromq=4.3.5=h6c54ac7_1
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\wkddk\miniconda3\envs\mse465project
